# enable debug
debug: true

build:
  image: sbejga/debian-ruby-node
  commands:
  - npm install --silent
  - bower install --allow-root --silent
  # create drone_meta.json by helper node.js app '.env_drone.js'
  # which will insert the drone environment variables e.g. commit, branch into json file
  - node .env_drone.js
  # to build production version with grunt
  # force because imagemin, svgmin fail?
  - grunt build

# publish to private docker registry
publish:
  docker:
    registry: tesla.stranged.de:5000
    username: $$TESLA_DOCKER_USER
    password: $$TESLA_DOCKER_REGISTRY_PASSWORD
    email: $$TESLA_DOCKER_USER
    repo: rotebuehl
    insecure: true

# trigger docker deploy (stop, rm, pull, run)
deploy:
  ssh:
    host:
     - $$SSH_HOST
    user: $$SSH_USER
    port: $$SSH_PORT
    sleep: 5
    commands:
      - ~/scripts/rotebuehl_latest.sh


# send email
notify:
  email:
    from: $$MAILGUN_FROM
    host: smtp.mailgun.org
    username: $$MAILGUN_USER
    password: $$MAILGUN_PASSWORD
    recipients:
      - $$MAILGUN_RECIPIENT

cache:
  mount:
    - node_modules
